component_management:
  default_rules:  # default rules that will be inherited by all components
    statuses:
      - type: project # in this case every component that doens't have a status defined will have a project type one
        target: auto
  individual_components:
    - component_id: module_devops  # this is an identifier that should not be changed
      name: devops
      paths:
        - devops/**
    - component_id: module_mlops
      name: mlops
      paths:
        - mlops/**
    - component_id: module_repositories
      name: repositories
      paths:
        - repositories/**
    - component_id: module_utils
      name: utils
      paths:
        - utils/**